[package]
name = "chiihou-client"
version.workspace = true
edition.workspace = true

[dependencies]
bot-core = { path = "../bot-core" }
bot-logic = { path = "../bot-logic" }
nostr-sdk.workspace = true
thiserror.workspace = true
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
